[project]
name = "upload-to-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=3.2.0",
    "flatdict>=4.0.1",
    "loguru>=0.7.3",
    "typer>=0.15.1",
]
